package android

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.0'
    }
}

plugins {
    id 'com.android.library'
}

group 'io.flutterfastkit.fk_user_agent'
version '2.2.0'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    namespace 'io.flutterfastkit.fk_user_agent'
    compileSdk flutter.compileSdkVersion

    defaultConfig {
        minSdk flutter.minSdkVersion
    }

    lint {
        disable 'InvalidPackage'
    }
}

